# -*- coding: utf-8 -*-
"""
Django settings for cbbweb project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from configurations import Configuration
from cbbweb.base_settings import BaseConfig
from cbbweb.dev_settings import Dev
from cbbweb.test_settings import Test
from cbbweb.prod_settings import Prod

try:
    from cbbweb.chx_settings import Chx
    from cbbweb.lc_settings import Lc
except ImportError:
    pass
